version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "7006:80"
    restart: always

  hr-page:
    build:
      context: ./hr-page
      dockerfile: Dockerfile
    ports:
      - "7007:80"
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3815:3815"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=admin234
      - DB_NAME=onboarding
      - DB_PORT=5432
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: postgres-db
    ports:
      - "5409:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
      POSTGRES_DB: onboarding
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:

